### ISSUE TITLE
Poor instructions, doesn't work.

### ISSUE THREAD

**Issue by Ainaemaet** [AlexSteiner30/Nervision#1]
Hello, decided to give this project a try - despite having rudimentary python knowledge I managed to get all the dependencies installed ok. 

The issue I am having (aside from the easily remediable fact that you say to run server.js in the AI folder, when all that is available is server.py) is that when running server.py I get the following 

FileNotFoundError: [Errno 2] No such file or directory: '../AI/TrainedModels/vertices.pt'

Are pretrained models not available?

**Comment by alexsteinerr** [comment]
Hi,  Pre trained models are available however they are trained on a small
fraction of the dataset
